from distutils.core import setup

import version


setup(name='microdrop',
      version=version.getVersion(),
      description='Microdrop is a graphical user interface for the DropBot '
                  'Digital Microfluidics control system',
      keywords='digital microfluidics dmf automation dropbot microdrop',
      author='Ryan Fobel and Christian Fobel',
      author_email='ryan@fobel.net, christian@fobel.net',
      url='http://microfluidics.utoronto.ca/microdrop',
      license='GPL',
      long_description='\n%s\n' % open('README.md', 'rt').read(),
      packages=['microdrop',
                'microdrop.gui',
                'microdrop.tests'],
      package_data={'microdrop.tests': ['devices/*', 'experiment_logs/*',
                                        'protocols/*', 'svg_files/*.svg',
                                        'buildbot/master.cfg'],
                    'microdrop.gui': ['glade/*.glade']},
      install_requires=['blinker', 'path', 'ipython', 'pyutilib', 'pyparsing',
                        'configobj', 'pyyaml', 'pyzmq', 'opencv-helpers',
                        'pygst-utils', 'geo-util', 'pygtkhelpers',
                        'labix-constraint', 'jsonrpc', 'flatland',
                        'microdrop_utility', 'svg_model', 'task_scheduler',
                        'application_repository',
                        'pygtk_textbuffer_with_undo'],
      dependency_links=['http://microfluidics.utoronto.ca/git/python___path.git/snapshot/da43890764f1ee508fe6c32582acd69b87240365.zip#egg=path-dev',
                        'https://github.com/cfobel/opencv_helpers/tarball/master#egg=opencv-helpers-dev',
                        'git+https://github.com/cfobel/pygst_utils.git@zeromq#egg=pygst-utils-dev',
                        'git+https://github.com/cfobel/microdrop_utility.git@master#egg=microdrop-utility-dev',
                        'git+https://github.com/cfobel/pygtk_textbuffer_with_undo.git@master#egg=pygtk-textbuffer-with-undo-dev',
                        'git+https://github.com/cfobel/application_repository.git@master#egg=application-repository-dev',
                        'git+https://github.com/cfobel/task_scheduler.git@master#egg=task-scheduler-dev',
                        'git+https://github.com/cfobel/svg_model.git@master#egg=svg-model-dev',
                        'https://github.com/cfobel/python___geo_util/tarball/master#egg=geo-util-dev',
                        'https://github.com/cfobel/pygtkhelpers/tarball/pre_object_tree#egg=pygtkhelpers-dev',
                        'https://github.com/cfobel/python___labix_constraint/tarball/master#egg=labix-constraint-dev',
                        'https://github.com/cfobel/python-jsonrpc/tarball/master#egg=jsonrpc-dev',
                        'http://microfluidics.utoronto.ca/git/python___flatland.git/snapshot/master.zip#egg=flatland-dev'])
